# This is a basic workflow to build and deploy images to Azure Container Registry.
name: IMAGE-BUILD-DEPLOY

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    types: [opened, synchronize, reopened, edited, closed]
    branches: [main]
  issue_comment:
    types: [created, edited]
  
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-image:
    outputs:
      IMAGE_NAME: ${{ steps.parse.outputs.IMAGE_NAME }}
      IMAGE_TAG: ${{ steps.parse.outputs.IMAGE_TAG }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: 'Check for build command'
        id: build
        uses: eliasmelgaco/pull-request-comment-trigger@v2.0.0
        with:
          trigger: '#build: ** ** **'
          allow_arguments: true

      - name: 'Parse build arguments'
        id: parse
        run: |
          echo "Build Parameters"
          echo "DOCKERFILE_PATH=${{ fromJson(steps.build.outputs.arguments)[0] }}" >> $GITHUB_ENV
          IMAGE_NAME=${{ fromJson(steps.build.outputs.arguments)[1] }}
          IMAGE_TAG=${{ fromJson(steps.build.outputs.arguments)[2] }}
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "IMAGE_NAME=$IMAGE_NAME" >> "$GITHUB_OUTPUT"
          echo "IMAGE_TAG=$IMAGE_TAG" >> "$GITHUB_OUTPUT"
        if: steps.build.outputs.triggered == 'true'
          
      - name: 'Build image'
        run: |
          FULL_IMAGE_TAG=${{ secrets.REGISTRY_LOGIN_SERVER }}/$IMAGE_NAME:$IMAGE_TAG
          docker build $DOCKERFILE_PATH -t $FULL_IMAGE_TAG
          mkdir -p /tmp/docker/artifacts
          docker save $FULL_IMAGE_TAG > /tmp/docker/artifacts/$IMAGE_NAME-$IMAGE_TAG.tar
        if: steps.build.outputs.triggered == 'true'
        
      - name: Temporarily save Docker image
        uses: actions/upload-artifact@v2
        with:
          name: docker-artifact
          path: /tmp/docker/artifacts
          retention-days: 1

    # This workflow contains a single job called "build"
  deploy-image:
      # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build-image
    if: github.event.pull_request.merged == true
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Login to ACR'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Retrieve saved Docker image
        uses: actions/download-artifact@v4
        with:
          name: docker-artifact
          path: /tmp/docker/artifacts 

      - name: 'Deploy image to ACR'
        env: 
          IMAGE_NAME: ${{ needs.build-image.outputs.IMAGE_NAME }}
          IMAGE_TAG: ${{ needs.build-image.outputs.IMAGE_TAG }}          
        run: |
          cd /tmp/docker/artifacts
          docker load < $IMAGE_NAME-$IMAGE_TAG.tar
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/$IMAGE_NAME:$IMAGE_TAG
