# This is a basic workflow to build and deploy images to Azure Container Registry.
name: IMAGE-BUILD-DEPLOY

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    types: [opened, synchronize, reopened, edited, closed]
    branches: [main]
  issue_comment:
    types: [created, edited]
  
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-image:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: 'Check for build command'
        id: build
        uses: eliasmelgaco/pull-request-comment-trigger@v2.0.0
        with:
          trigger: '#build: ** ** **'
          allow_arguments: true

      - name: 'Parse build arguments'
        run: |
          echo "Build Parameters"
          echo "DOCKERFILE_PATH=${{ fromJson(steps.build.outputs.arguments)[0] }}" >> $GITHUB_ENV
          echo "IMAGE_NAME=${{ fromJson(steps.build.outputs.arguments)[1] }}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ fromJson(steps.build.outputs.arguments)[2] }}" >> $GITHUB_ENV
        if: steps.build.outputs.triggered == 'true'
          
      - name: 'Build image'
        run: |
          docker build $DOCKERFILE_PATH -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/$IMAGE_NAME:$IMAGE_TAG
        if: steps.build.outputs.triggered == 'true'

    # This workflow contains a single job called "build"
  deploy-image:
      # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build-image
    if: github.event.pull_request.merged == true
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Login to ACR'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
        
      - name: 'Deploy image to ACR'
        run: |
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/$IMAGE_NAME:$IMAGE_TAG
